openapi: 3.1.0
info:
  title: Channel Engagement Service API
  description: |-
    The Channel Engagment Service (CES) API provides the ability to interact securely with the client and advice domains for a client associated to an adviser or linked assistant.
    The API is secured by OAuth2.
    The FSP context need to be provided explicitly for verification of user context with the context key (broker house code-broker code combination).
    Relationships between an adviser and client are verified by using the supplied clientKey
  contact:
    name: Team Samurais
    email: franco.opperman@momentum.co.za
  version: v1.0
servers:
  - url: 'https://channel-engagament-service.adv-slstst.momentum.co.za/channel-engagament-service'
    description: Internal testing server
  - url: 'https://channel-engagament-service.momentum.co.za/channel-engagament-service'
    description: External testing server
  - url: 'https://channel-engagament-service.adv-slspre.momentum.co.za/channel-engagament-service'
    description: Internal pre-live server
  - url: 'https://channel-engagament-service.momentum.co.za/channel-engagament-service'
    description: External pre-live server
  - url: 'https://channel-engagament-service.adv-sls.momentum.co.za/channel-engagament-service'
    description: Internal production server
  - url: 'https://channel-engagament-service.momentum.co.za/channel-engagament-service'
    description: External production server
paths:
  /v1/natural-persons/query:
    post:
      summary: Natural Person query resource
      responses:
        '200':
          description: List of Natural Persons retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NaturalPerson'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '401':
          description: Authentication required. Authentication token is missing or is invalid in some way.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Requesting (authenticated) party is not authorised to access requested information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
      operationId: retrieveNaturalPersonByCriteria
      description: Filter Natural Person collection by search criteria
      security:
        - access_token: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NaturalPersonQuery'
        description: Retrieve all Natural Person by search criteria
      tags:
        - Query
    parameters: []
  /v1/juristic-entities/query:
    post:
      summary: Juristic Entity query resource
      responses:
        '200':
          description: List of Juristic Entities retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JuristicEntity'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '401':
          description: Authentication required. Authentication token is missing or is invalid in some way.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Requesting (authenticated) party is not authorised to access requested information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
      operationId: retrieveJuristicEntitiesByCriteria
      description: Retrieve all Juristic Entities by search criteria
      security:
        - access_token: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JuristicEntityQuery'
        description: Retrieve all JuristicEntities by search criteria
      tags:
        - Query
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  securitySchemes:
    access_token:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
tags:
  - name: Creation
  - name: Publish
  - name: Query
  - name: Removal
  - name: Replacement
  - name: Retrieval
  - name: Update
  - name: ActionXXX
